version = 1

exclude_patterns = [
    ".vscode/**",
    "config/*.config.*.js",
    "lib/**",
    "public/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest"
  ]
  plugins = ["react"]
  module_system = "es-modules"
